export {
    Add as AddIcon,
    CheckBox as CheckBoxIcon,
    Cancel as CancelIcon,
    Check as CheckIcon,
    Close as CloseIcon,
    CloseFullscreen as CloseFullscreenIcon,
    Delete as DeleteIcon,
    Edit as EditIcon,
    EuroSymbol as EuroSymbolIcon,
    ExpandMore as ExpandMoreIcon,
    Mail as MailIcon,
    Print as PrintIcon,
    Person as PersonIcon,
    PersonSearch as PersonSearchIcon,
    Refresh as RefreshIcon,
    Save as SaveIcon,
} from "@mui/icons-material";
